name: Catta Build Pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Build APK
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug
          # Smart find: finds the generated debug APK and renames it to catta.apk
          find . -name "*-debug.apk" -exec mv {} ./catta.apk \;
        working-directory: .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Catta-Build
          # Now the APK is in the root folder because of the 'mv' command above
          path: catta.apk
          
