name: Catta Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Force Build
        run: |
          # Use system gradle to avoid wrapper errors
          gradle assembleDebug --stacktrace
        working-directory: .

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Catta-Release
          # This finds the APK wherever the server put it
          path: "**/*.apk"
          
