name: Catta Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Force Build
        run: |
          # Use system gradle and skip the wrapper if it's broken
          gradle assembleDebug --stacktrace
          
          # This will show you exactly where the APK is in the logs
          echo "Listing all generated APKs:"
          find . -name "*.apk"
        working-directory: .

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Catta-Release
          # Using the wildcard to grab the file from the subfolders
          path: "app/build/outputs/apk/debug/*.apk"
          
